#! /bin/bash

# source the ciop functions (e.g. ciop-log)
source ${ciop_job_include}
set -x
# define the exit codes
SUCCESS=0
ERR_PAR=2
ERR_MOSAIC=3
ERR_MULTILOOK=4

# create a TMPDIR in /tmp to use GAMMA
UUIDTMP="/tmp/`uuidgen`"
mkdir -p ${UUIDTMP}
export TMPDIR=${UUIDTMP}
chmod 777 ${UUIDTMP}

export PATH=/opt/gamma/DIFF/bin:/opt/gamma/DISP/bin/:/opt/gamma/ISP/bin:/opt/gamma/LAT/bin:$PATH

# add a trap to exit gracefully
function cleanExit ()
{
  local retval=$?
  local msg=""
  case "$retval" in
    $SUCCESS) msg="Processing successfully concluded";;
    $ERR_PAR) msg="Failed to ingest the Sentinel-1 product with GAMMA";;
    $ERR_MOSAIC) msg="Failed to create the S1 SLC mosaic";;
    $ERR_MULTILOOK) msg="Failed to multi look";;
  *) msg="Unknown error";;
  esac

  [ "$retval" != "0" ] && ciop-log "ERROR" "Error $retval - $msg, processing aborted" || ciop-log "INFO" "$msg"
  exit $retval
}

trap cleanExit EXIT

function ingest() {
 
 local header=$1
 
 for polarization in $( echo 'HH' 'VV' )
 do
   xpath="//level1Product/productComponents/imageData[polLayer/text()=\"${polarization}\"]/file/location/filename/text()"
   cos=$( dirname ${header})/$( xmllint -xpath ${xpath} ${header} )
   par_TX_SLC \
    ${header} \
    ${cos} \
    ${TMPDIR}/${polarization}.slc.par \
    ${TMPDIR}/${polarization}.slc \
    ${polarization} &> ${TMPDIR}/par_TX_SLC_${polarization}.log || return 4 
  done

}

function mlook() {
  
  for polarization in $( echo 'HH' 'VV' )
  do
    multi_look \
      ${TMPDIR}/${polarization}.slc \
      ${TMPDIR}/${polarization}.slc.par \
      ${TMPDIR}/${polarization}.mli \
      ${TMPDIR}/${polarization}.mli.par 6 4 &> ${TMPDIR}/multi_look_${polarization}.log || return 6
  done
}

function radcm() {

  for polarization in $( echo 'HH' 'VV' )
  do
    radcal_MLI \
      ${TMPDIR}/${polarization}.mli \
      ${TMPDIR}/${polarization}.slc.par - \
      ${TMPDIR}/${polarization}.cmli - 0 0 1 0.0 - &> ${TMPDIR}/radcal_MLI_${polarization}.lop || return 8
  done
}

function geocodeb() {

  local r_samples=$1
  local w=$2

  for polarization in $( echo 'HH' 'VV' )
  do
    geocode_back \
      ${TMPDIR}/${polarization}.cmli \
      ${r_samples} \
      ${TMPDIR}/DEM.lookup_table \
      ${TMPDIR}/${polarization}.cmli.geocoded ${w} - 0 0 &> ${TMPDIR}/geocode_back_${polarization}.log || return 10
   done

}

function ras() {

  local r_samples=$1

  for polarization in $( echo 'HH' 'VV' )
  do
    raspwr \
      ${TMPDIR}/${polarization}.cmli \
      ${range_samples} \
      1 0 1 1 - - - \
      ${TMPDIR}/${polarization}.cmli.ras &> ${TMPDIR}/raspwr_${polarization}.log
  done
}

function main () {

  while read input
  do
    enclosure="$( opensearch-client ${input} enclosure )"
    local_input="$( ciop-copy -z -o $TMPDIR ${enclosure} )"

    leader="$( tar tfz ${local_input} | grep "\.xml$" | sed 's#.*/\(.*\)#\1#g' | grep "^T.*\.xml" )"
   
    leader_path="$( tar tfz ${local_input} | grep ${leader} )"

    # extract leader file
    tar -xzOf ${local_input} ${leader_path} > ${TMPDIR}/${leader}
  
    ingest \
      ${TMPDIR}/${leader} || return $?

    mlook || return $? 

    radcm || return $?

    gec_map \
      ${TMPDIR}/HH.mli.par - \
      ${TMPDIR}/${DEM}.par 0.0 \
      ${TMPDIR}/DEM.dem_seg.par \
      ${TMPDIR}/DEM.lookup_table 20 20 &> ${TMPDIR}/gec_map.log || return $?

      width=$( cat $output/DEM.dem_seg.par | grep width | tr  -s " " | cut -d " " -f 2 )
      range_samples=$( cat $output/HH.mli.par | grep range_samples | tr  -s " " | cut -d " " -f 2 )

      geocodeb ${range_samples} ${width} || return $?

    ratio \
      ${TMPDIR}/HH.cmli \
      ${TMPDIR}/VV.cmli \
      ${TMPDIR}/HHVV \
      ${range_samples} &> ${TMPDIR}/ratio.log || return $?

    ras

    raspwr \
      ${TMPDIR}/HHVV \
      ${range_samples} \
      1 0 1 1 - - - \
      ${TMPDIR}/HHVV.cmli.ras &> ${TMPDIR}/raspwr_HHVV.log || return $?

    ras_to_rgb \
      ${TMPDIR}/HH.cmli.ras \
      ${TMPDIR}/VV.cmli.ras \
      ${TMPDIR}/HHVV.cmli.ras \
      ${TMPDIR}/RGB.bmp &> ${TMPDIR}/ras_to_rgb.log || return $? 

    geocode_back \
      ${TMPDIR}/RGB.bmp \
      ${range_samples} \
      ${TMPDIR}/DEM.lookup_table \
      ${TMPDIR}/RGB.geocoded.utm.bmp \
      ${width} - 0 2 &> ${TMPDIR}/geocode_back_RGB.log || return $?

  done
}

# retrieve the DEM
mkdir -p ${TMPDIR}/workdir/dem
wps_result="$( ciop-browseresults -r ${CIOP_WF_RUN_ID} -j node_dem -w | tr -d '\r' | tr '\n' ';' | cut -d ";" -f 1)"
# extract the result URL
curl -L -o ${TMPDIR}/workdir/dem/dem.tgz "${wps_result}" 2> /dev/null
tar xzf ${TMPDIR}/workdir/dem/dem.tgz -C ${TMPDIR}/workdir/dem/

cat | main || exit $?
